local Unlocks = {
  { name = "Flame Thrower",       mob = "Gobmachine G-VI", source = "Brayflox's Longstop (Hard)", level = 50 },
  { name = "Aqua Breath",         mob = "Ultros", source = "The Dragon's Neck", level = 50 },
  { name = "Flying Frenzy",       map = 180, node = 16, mob = "Cornu", level = 50, source = "World" },
  { name = "Drill Cannons",       map = 147, node = 21, pos = { x = -262.19, y = 83.26, z = -309.62 }, mob = 'Magitek Vanguard H-2', unlock = {8138}, level = 50, source = "World" },
  { name = "High Voltage",        mob = "ADS", source = "The Binding Coil of Bahamut - Turn 1", level = 50 },
  { name = "Loom",                map = 147, node = 21, mob = 'Flame Sergeant Dalvag', level = 50, source = "World" },
  { name = "Final Sting",         map = 134, node = 45, pos = { x = -266.80, y = 22.27, z = -395.01 }, level = 13, mob = "Killer Wespe", unlock = { 8134 }, source = "World" },
  { name = "Song of Torment",     mob = "Siren", source = "Pharos Sirius", level = 50 },
  { name = "Glower",              mob = "Coincounter", source = "The Aurum Vale", level = 47 },
  { name = "Plaincracker",        map = 154, node = 7,  pos = { x = -62.82, y = -45.06, z = 363.31 }, mob = 'Clay Golem', unlock = {30}, level = 28, source = "World" },
  { name = "Bristle",             map = 152, node = 4,  pos = { x = -232.7, y = 3.26, z = 106.59 }, mob = 'Wild Boar', unlock = {16}, level = 21, source = "World" },
  { name = "White Wind",          map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Learn 10 Blue Magic Spells", source = "Wayward Gaheel Ja", level = 20 },
  { name = "Level 5 Petrify",     mob = "Manor Sentry", source = "Haukke Manor", level = 28 },
  { name = "Sharpened Knife",     map = 139, node = 15, mob = "Marberry", level = 50, source = "World" },
  { name = "Ice Spikes",          map = 148, node = 3,  pos = { x = 238.34,  y = 24.02, z = 206.26  }, mob = 'Trickster Imp', unlock = {21}, level = 9, source = "World" },
  { name = "Blood Drain",         map = 135, node = 10, pos = { x = 278.76,  y = 74.03, z = -272.06 }, mob = "Cave Bat", unlock = { 364 }, source = "World", level = 7 },
  { name = "Acorn Bomb",          map = 152, node = 4,  pos = { x = -417.17, y = 0.34,  z = 202.57  }, mob = 'Treant Sapling', unlock = {128}, level = 14, source = "World" },
  { name = "Bomb Toss",           map = 134, node = 45, pos = { x = 120.05,  y = 49.66, z = 10.21   }, mob = "Goblin", unlock = { 367, 3099 }, source = "World", level = 5 },
  { name = "Off-guard",           map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Learn 5 Blue Magic Spells", source = "Wayward Gaheel Ja", level = 1 },
  { name = "Self-destruct",       map = 140, node = 17, pos = { x = 287.80,  y = 62.12, z = -197.17 }, mob = 'Glide Bomb', unlock = {8135}, level = 12, source = "World" },
  { name = "Transfusion",         map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Learn 20 Blue Magic Spells", source = "Wayward Gaheel Ja", level = 1 },
  { name = "Faze",                map = 135, node = 10, pos = { x = -146.86, y = 1.36,  z = 686.22  }, mob = "Quirin Eggdigger", unlock = { 350 }, level = 13, source = "World" },
  { name = "Flying Sardine",      map = 137, node = 11, pos = { x =  304.19, y = 39.01, z = 720.27  }, mob = 'Apkallu', unlock = {341}, level = 30, source = "World" },
  { name = "Snort",               mob = "Typhon", source = "The Dragon's Neck", level = 50 },
  { name = "4-tonze Weight",      mob = "Ultros", source = "The Dragon's Neck", level = 50 },
  { name = "The Look",            mob = "Anantabooga", source = "Amdapor Keep", level = 50 },
  { name = "Bad Breath",          map = 148, node = 3, pos = { x = -382.4, y = 52.87, z = -23.06 }, mob = 'Stroper', unlock = {238}, level = 31, source = "World" },
  { name = "Diamondback",         mob = "Cuca Fera", source = "The Stone Vigil (Hard)", level = 50 },
  { name = "Mighty Guard",        map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Learn 10 Blue Magic Spells", source = "Wayward Gaheel Ja", level = 1 },
  { name = "Sticky Tongue",       map = 135, node = 10, pos = { x =  140.95, y = 35.67, z =   53.78 }, mob = "Cane Toad", unlock = { 895 }, level = 2, source = "World" },
  { name = "Toad Oil",            map = 140, node = 17, pos = { x = -275.02, y = 15.9,  z = -731.03 }, mob = 'Giggling Gigantoad', unlock = {8136}, level = 24, source = "World" },
  { name = "The Ram's Voice",     mob = "Chimera", source = "Cutter's Cry", level = 38 },
  { name = "The Dragon's Voice",  mob = "Chimera", source = "Cutter's Cry", level = 38 },
  { name = "Missile",             mob = "Enkidu", source = "Battle in the Big Keep", level = 50 },
  { name = "1000 Needles",        map = 146, node = 19, pos = { x = -234.10, y = 16.62, z = -273.23 }, mob = 'Sabotender Bailaor', unlock = {8137}, level = 26, source = "World" },
  { name = "Ink Jet",             mob = 'Kraken', source = "Sastasha (Hard)", level = 50 },
  { name = "Fire Angon",          mob = "Frumious Koheel Ja", source = "The Wanderer's Palace (Hard)", level = 50 },
  { name = "Moon Flute",          map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Clear 10 Stages", source = "The Masked Carnivale", level = 50 },
  { name = "Tail Screw",          mob = 'Kraken', source = "Sastasha (Hard)", level = 50 },
  { name = "Mind Blast",          mob = 'Galvanth the Dominator', source = "The Tam-Tara Deepcroft", level = 16 },
  { name = "Doom",                map = 131, node = 35, pos = { x = 67.77,   y = 14.01, z =  88.98  }, mob = "Clear 20 Stages", source = "The Masked Carnivale", level = 50 },
  { name = "Peculiar Light",      map = 156, node = 24, pos = { x = -413.43, y = -4.57, z = -538.86 }, mob = 'Lentic Mudpuppy', source = "World", unlock = {8139}, level = 45 },
  { name = "Feather Rain",        mob = 'Garuda', source = 'The Howling Eye (Extreme)', level = 50 },
  { name = "Eruption",            mob = 'Ifrit', source = 'The Bowl of Embers', level = 20 },
  { name = "Mountain Buster",     mob = 'Titan', source = 'The Navel (Hard)', level = 50 },
  { name = "Shock Strike",        mob = 'Ramuh', source = 'The Striking Tree (Hard)', level = 50 },
  { name = "Glass Dance",         mob = 'Shiva', source = 'Akh Afah Ampitheatre (Extreme)', level = 50 },
  { name = "Veil of the Whorl",   mob = 'Leviathan', source = 'The Whorleater (Hard)', level = 50 },
  { name = "Alpine Draft",        mob = 'Opinicus', source = 'The Dust Vigil', level = 51 },
  { name = "Protean Wave",        map = 621, node = 102, pos = { x = -651.84, y = 50, z = -4.22 }, mob = "Salt and Light", source = "World", level = 70 },
  { name = "Northerlies" },
  { name = "Electrogenesis",      },
  { name = "Kaltstrahl" },
  { name = "Abyssal Transfixion" },
  { name = "Chirp" },
  { name = "Eerie Soundwave",     mob = "Enkidu", source = "Battle in the Big Keep", level = 50 },
  { name = "Pom Cure" },
  { name = "Gobskin" },
  { name = "Magic Hammer" },
  { name = "Avail" },
  { name = "Frog Legs" },
  { name = "Sonic Boom",          map = 180, node = 16, pos = { x = -116.63, y = 64.74, z = -205.56 }, mob = "Cornu", level = 50, source = "World" },
  { name = "Whistle" },
  { name = "White Knight's Tour" },
  { name = "Black Knight's Tour" },
  { name = "Level 5 Death" },
  { name = "Launcher" },
  { name = "Perpetual Ray" },
  { name = "Cactguard" },
  { name = "Revenge Blast" },
  { name = "Angel Whisper" },
  { name = "Exuviation" },
  { name = "Reflux" },
  { name = "Devour" },
  { name = "Condensed Libra" },
  { name = "Aetheric Mimicry" },
  { name = "Surpanakha" },
  { name = "Quasar" },
  { name = "J Kick" },
  { name = "Triple Trident" },
  { name = "Tingle" },
  { name = "Tatami-gaeshi" },
  { name = "Cold Fog" },
  { name = "Stotram" },
  { name = "Saintly Beam" },
  { name = "Feculent Flood" },
  { name = "Angel's Snack" },
  { name = "Chelonian Gate" },
  { name = "The Rose of Destruction" },
  { name = "Basic Instinct",       map = 139, node = 15, pos = { x = -617.09, y = 0, z = -20.5 }, mob = 'Master Coeurl', unlock = {9911}, level = 24, source = "World" },
  { name = "Ultravibration" },
  { name = "Blaze" },
  { name = "Mustard Bomb" },
  { name = "Dragon Force" },
  { name = "Aetherial Spark" },
  { name = "Hydro Pull" },
  { name = "Malediction of Water" },
  { name = "Choco Meteor" },
  { name = "Matra Magic" },
  { name = "Peripheral Synthesis" },
  { name = "Both Ends" },
  { name = "Phantom Flurry" },
  { name = "Nightbloom" },
}

return Unlocks