local Unlocks = {
  { name = "Flame Thrower", id = 0 },
  { name = "Aqua Breath", id = 0 },
  { name = "Flying Frenzy", mob = "Cornu", map = 16, pos = { x = -116.63, y = 64.74, z = -205.56 }, level = 50 },
  { name = "Drill Cannons", id = 0 },
  { name = "High Voltage", id = 0},
  { name = "Loom", id = 0},
  { name = "Final Sting", map = 45, pos = { x = -266.80, y = 22.27, z = -395.01 }, level = 13, mob = "Killer Wespe", unlock = { 8134 } },
  { name = "Song of Torment", id = 0},
  { name = "Glower", id = 0},
  { name = "Plaincracker", map = 7, pos = { x = -62.82, y = -45.06, z = 363.31 }, mob = 'Clay Golem', unlock = {30}, level = 28 },
  { name = "Bristle", id = 0},
  { name = "White Wind", id = 0},
  { name = "Level 5 Petrify", id = 0},
  { name = "Sharpened Knife", map = 15, level = 50, mob = "Marberry", pos = { x = 435.88, y = 4.11, z = 83.29 } },
  { name = "Ice Spikes", id = 0},
  { name = "Blood Drain", map = 10, pos = { x = 278.76, y = 74.03, z = -272.06 }, level = 7, mob = "Cave Bat", unlock = { 364 } },
  { name = "Acorn Bomb", id = 0},
  { name = "Bomb Toss", map = 45, pos = { x = 120.05, y = 49.66, z = 10.21 }, level = 5, mob = "Goblin", unlock = { 367, 3099 } },
  { name = "Off-guard", id = 0},
  { name = "Self-destruct", map = 17, pos = { x = 287.8, y = 62.12, z = -197.17 }, mob = 'Glide Bomb', unlock = {8135}, level = 12 },
  { name = "Transfusion", id = 0},
  { name = "Faze", map = 10, pos = { x = -146.86, y = 1.36, z = 686.22 }, mob = "Quirin Eggdigger", unlock = { 350 }, level = 13 },
  { name = "Flying Sardine", map = 11, pos = { x = 304.19, y = 39.01, z = 720.27 }, mob = 'Apkallu', unlock = {341}, level = 30 },
  { name = "Snort", id = 0},
  { name = "4-tonze Weight", id = 0},
  { name = "The Look", id = 0},
  { name = "Bad Breath", id = 0},
  { name = "Diamondback", id = 0},
  { name = "Mighty Guard", id = 0},
  { name = "Sticky Tongue", map = 10, pos = { x = 140.94761657715, y = 35.665096282959, z = 53.779174804688 }, level = 2, mob = "Cane Toad", unlock = { 895 } },
  { name = "Toad Oil", id = 0},
  { name = "The Ram's Voice", id = 0},
  { name = "The Dragon's Voice", id = 0},
  { name = "Missile", id = 0},
  { name = "1000 Needles", id = 0},
  { name = "Ink Jet", id = 0},
  { name = "Fire Angon", id = 0},
  { name = "Moon Flute", id = 0},
  { name = "Tail Screw", id = 0},
  { name = "Mind Blast", id = 0},
  { name = "Doom", id = 0},
  { name = "Peculiar Light", id = 0},
  { name = "Feather Rain", id = 0},
  { name = "Eruption", id = 0},
  { name = "Mountain Buster", id = 0},
  { name = "Shock Strike", id = 0},
  { name = "Glass Dance", id = 0},
  { name = "Veil of the Whorl", id = 0},
  { name = "Alpine Draft", id = 0},
  { name = "Protean Wave", id = 0},
  { name = "Northerlies", id = 0},
  { name = "Electrogenesis", id = 0},
  { name = "Kaltstrahl", id = 0},
  { name = "Abyssal Transfixion", id = 0},
  { name = "Chirp", id = 0},
  { name = "Eerie Soundwave", id = 0},
  { name = "Pom Cure", id = 0},
  { name = "Gobskin", id = 0},
  { name = "Magic Hammer", id = 0},
  { name = "Avail", id = 0},
  { name = "Frog Legs", id = 0},
  { name = "Sonic Boom", mob = "Cornu", map = 16, pos = { x = -116.63, y = 64.74, z = -205.56 }, level = 50 },
  { name = "Whistle", id = 0},
  { name = "White Knight's Tour", id = 0},
  { name = "Black Knight's Tour", id = 0},
  { name = "Level 5 Death", id = 0},
  { name = "Launcher", id = 0},
  { name = "Perpetual Ray", id = 0},
  { name = "Cactguard", id = 0},
  { name = "Revenge Blast", id = 0},
  { name = "Angel Whisper", id = 0},
  { name = "Exuviation", id = 0},
  { name = "Reflux", id = 0},
  { name = "Devour", id = 0},
  { name = "Condensed Libra", id = 0},
  { name = "Aetheric Mimicry", id = 0},
  { name = "Surpanakha", id = 0},
  { name = "Quasar", id = 0},
  { name = "J Kick", id = 0},
  { name = "Triple Trident", id = 0},
  { name = "Tingle", id = 0},
  { name = "Tatami-gaeshi", id = 0},
  { name = "Cold Fog", id = 0},
  { name = "Stotram", id = 0},
  { name = "Saintly Beam", id = 0},
  { name = "Feculent Flood", id = 0},
  { name = "Angel's Snack", id = 0},
  { name = "Chelonian Gate", id = 0},
  { name = "The Rose of Destruction", id = 0},
  { name = "Basic Instinct", map = 15, pos = { x = -623.8, y = -3.5, z = -44.2 }, mob = "Master Coeurl", unlock = {9911}, level = 24 },
  { name = "Ultravibration", id = 0},
  { name = "Blaze", id = 0},
  { name = "Mustard Bomb", id = 0},
  { name = "Dragon Force", id = 0},
  { name = "Aetherial Spark", id = 0},
  { name = "Hydro Pull", id = 0},
  { name = "Malediction of Water", id = 0},
  { name = "Choco Meteor", id = 0},
  { name = "Matra Magic", id = 0},
  { name = "Peripheral Synthesis", id = 0},
  { name = "Both Ends", id = 0},
  { name = "Phantom Flurry", id = 0},
  { name = "Nightbloom", id = 0},
}

return Unlocks